// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6jJl1te8qkjS09csFTMNoHZoqoooZo8k',
    appId: '1:435478095990:web:ccb0a8f354b89bc3a75757',
    messagingSenderId: '435478095990',
    projectId: 'vk-shopping-cart',
    authDomain: 'vk-shopping-cart.firebaseapp.com',
    storageBucket: 'vk-shopping-cart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV1siFlzLGf8pd3sQDIrN_8Ks7CgT0zZo',
    appId: '1:435478095990:android:95e723ee3e197441a75757',
    messagingSenderId: '435478095990',
    projectId: 'vk-shopping-cart',
    storageBucket: 'vk-shopping-cart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABvziWGWbvbhMLS9vVxhD5mpb2p_FgXlw',
    appId: '1:435478095990:ios:ad84af68df9c97f1a75757',
    messagingSenderId: '435478095990',
    projectId: 'vk-shopping-cart',
    storageBucket: 'vk-shopping-cart.appspot.com',
    iosBundleId: 'com.example.vkShopping',
  );
}
